# Generated by Django 3.0.3 on 2020-03-02 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Headset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('connections', models.CharField(max_length=50)),
                ('resolution', models.CharField(max_length=50)),
                ('refresh_rate', models.CharField(max_length=50)),
                ('motion_tracking', models.CharField(max_length=50)),
                ('controls', models.CharField(max_length=50)),
                ('hardware_platform', models.CharField(max_length=50)),
                ('software_platform', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('headset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headsets', to='headsets.Type')),
            ],
        ),
    ]
