# Generated by Django 3.0.3 on 2020-02-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('headset_type', models.CharField(max_length=50)),
                ('connections', models.CharField(max_length=50)),
                ('resolution', models.CharField(max_length=50)),
                ('refresh_rate', models.CharField(max_length=50)),
                ('motion_tracking', models.CharField(max_length=50)),
                ('controls', models.CharField(max_length=50)),
                ('hardware_platform', models.CharField(max_length=50)),
                ('software_platform', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
