# Generated by Django 3.0.3 on 2020-02-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headset',
            name='image',
            field=models.CharField(default='Insert Image', max_length=300),
        ),
    ]
