# Generated by Django 3.0.3 on 2020-02-28 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headsets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headset_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='headset',
            name='headset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headsets', to='headsets.Type'),
        ),
    ]
