# Generated by Django 3.0.3 on 2020-02-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headsets', '0002_auto_20200228_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='headset_type',
            new_name='model_type',
        ),
    ]
